export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';

export const SAVE_VIDEO_SUCCESS = 'SAVE_VIDEO_SUCCESS';
export const SAVE_VIDEO_FAILURE = 'SAVE_VIDEO_FAILURE';